macxred/pyledger

pyledger/ledger_engine.py
pyledger/standalone_ledger.py

This PR covers changes from the [Review class hierarchy #62](https://github.com/macxred/cashctrl_ledger/issues/62) issue
@lasuk Please review the changes and provide feedback or approval for merging.

Feat: move methods to correct class

---

.github/workflows/linter.yml
.github/workflows/security.yml
.github/workflows/tests.yml
pyledger/__init__.py
pyledger/constants.py
pyledger/ledger_engine.py
pyledger/standalone_ledger.py
requirements.txt
setup.py

This PR covers changes to integrate the `consistent_df` package and use the `enforce_dtypes()` method to ensure robust type consistency. All methods that previously used the `astype()` approach have been replaced with `enforce_dtypes()`. Additionally, a constants file has been created to contain all field types.
@lasuk Please review the changes and provide feedback or approval for merging.

Feat: use consistent_df package 

---

pyledger/ledger_engine.py
pyledger/memory_ledger.py
pyledger/standalone_ledger.py
pyledger/test_ledger.py
tests/base_test_clear.py
tests/base_test_dump_restore.py
tests/test_clear.py
tests/test_dump_restore.py

This PR covers changes of creating `dump` and `restore` logic along with adding corresponding Base test
@lasuk Please review the changes and provide feedback or approval for merging

Feat: dump and restore logic

---

pyledger/ledger_engine.py
tests/__init__.py
tests/base_accounts.py
tests/base_test.py
tests/base_test_dump_restore_clear.py
tests/base_test_ledger.py
tests/base_vat_codes.py

1. **Resolve Incoherence in Testing Data**: Ensure consistency across the testing datasets, aligning them with the updated logic and expected outcomes.
2. **Update `dump()` and `restore()` Interface**: Modify the interface for `dump()` and `restore()` to reflect new requirements or implementation changes, improving clarity and functionality.
3. **Define `BaseTest` Class**: Introduce a `BaseTest` class that will store and manage a common set of data used across different test cases, promoting reusability and reducing redundancy in test setup.
4. **Update Error Handling in Tests**: Revise tests that expect errors to include the error class and error message as arguments. This enhances test readability and ensures precise error handling in expected failure scenarios.
This PR is crucial for …

Feat: modify base tests

---

README.md
pyledger/__init__.py
pyledger/external_ledger.py
pyledger/persistent_ledger.py
pyledger/text_ledger.py

**Description:**  
Introduces `PersistentLedger` for persistent data storage and `ExternalLedger` for integration with external accounting systems, extending PyLedger’s modularity for various storage and integration needs.

Feat: Refactor class hierarchy

---

README.md
pyledger/__init__.py
pyledger/constants.py
pyledger/ledger_engine.py
pyledger/memory_ledger.py
pyledger/standalone_ledger.py
pyledger/storage_entity.py
pyledger/tests/__init__.py
pyledger/tests/base_accounts.py
pyledger/tests/base_tax_codes.py
pyledger/tests/base_test.py
pyledger/tests/base_test_assets.py
pyledger/tests/base_test_dump_restore_clear.py
pyledger/tests/base_test_ledger.py
pyledger/tests/base_test_price_history.py
pyledger/tests/base_test_revaluation.py
pyledger/tests/test_accounts.py
pyledger/tests/test_price_history.py
pyledger/tests/test_revaluations.py

In this PR, we introduced a new architecture for storing accounting entities, applying a standardized approach across all accounting entities currently handled by the `MemoryLedger`. This update provides a consistent framework for managing data and ensures uniformity in operations across entities. At present, this new structure is implemented only for the `MemoryLedger`, but we plan to extend it to the `TextLedger` in the next phase.

Feat: delegate storage

---

pyledger/constants.py
pyledger/standalone_ledger.py
pyledger/storage_entity.py
pyledger/tests/test_text_ledger_accounts.py
pyledger/tests/test_text_ledger_assets.py
pyledger/tests/test_text_ledger_dump_restore_clear.py
pyledger/tests/test_text_ledger_ledger.py
pyledger/tests/test_text_ledger_price_history.py
pyledger/tests/test_text_ledger_revaluations.py
pyledger/tests/test_text_ledger_tax_codes.py
pyledger/text_ledger.py

This PR introduces a CSV-based storage approach for entity data, implemented within the `TextLedger` class.
- **CSV Storage Entity Design**: Added `LedgerCSVDataFrameEntity` and `CSVDataFrameEntity` classes.
- **TextLedger Integration**: Applied the new CSV storage approach to `TextLedger`.
- **Expanded Test Coverage**: Added missing tests for `TextLedger` entities, including price history and revaluations, to improve reliability and coverage.

Feat: define CSV storage entity

---

pyledger/ledger_engine.py

This PR adds new methods for managing settings, providing:
- A clear and consistent architecture.
- Greater flexibility for customization and future changes.
These improvements simplify settings handling and enhance maintainability.

Improve settings architecture

---

pyledger/__init__.py

This PR introduces the `ExternalTabularEntity` class, designed to facilitate seamless integration with external systems.

 Add ExternalTabularEntity class

---

pyledger/ledger_engine.py
pyledger/memory_ledger.py
pyledger/standalone_ledger.py
pyledger/storage_entity.py
pyledger/tests/test_serialized_ledger_cache.py
pyledger/text_ledger.py

This PR goal is to add caching for the `serialized_ledger()` method and design a mechanism for invalidating it.

Cache serialized ledger

---

pyledger/storage_entity.py
pyledger/tests/test_text_ledger_accounts.py
pyledger/tests/test_text_ledger_ledger.py

This PR introduces a mechanism to preserve extra columns when adding or modifying entity data.

Keep extra columns functionality

---

pyledger/helpers.py
pyledger/ledger_engine.py
pyledger/tests/test_first_elements_as_str.py
pyledger/tests/test_sanitize.py

This PR goal is to implement sanitize_ assets and price methods

Sanitize assets and prices

---

pyledger/ledger_engine.py
pyledger/standalone_ledger.py
pyledger/tests/test_sanitize.py

This PR goal is to implement method that sanitize revaluations data

Sanitize revaluations

---

pyledger/ledger_engine.py
pyledger/tests/test_sanitize.py

This PR goal is to implement sanitize methods for tax code and account entities.

Sanitize tax code and account

---

pyledger/ledger_engine.py
pyledger/standalone_ledger.py
pyledger/tests/base_test_price_history.py

This PR goal is to define `report_amount()` method in the `LedgerEngine` class.

Define `report_amount()` method

---

pyledger/__init__.py
pyledger/helpers.py
pyledger/storage_entity.py
pyledger/tests/test_save_files.py

Insert `MultiCSVEntity` into the class hierarchy for tabular data storage.

Store tabular data in multiple CSV files

---

pyledger/ledger_engine.py
pyledger/tests/base_test_dump_restore_clear.py
pyledger/tests/test_sanitize.py

This PR goal is to define a method that sanitizes ledger entries

Define Sanitize ledger method

---

pyledger/ledger_engine.py
pyledger/standalone_ledger.py
pyledger/tests/base_test.py
pyledger/tests/base_test_accounts.py
pyledger/tests/base_test_dump_restore_clear.py
pyledger/tests/base_test_ledger.py
pyledger/tests/test_serialized_ledger_cache.py

This PR goal is to implement profit center filtering logic for account balance and account history.

Profit centers for account balance and history

---

docs/TextLedger.md
pyledger/constants.py
pyledger/ledger_engine.py
pyledger/tests/base_test.py
pyledger/tests/base_test_accounts.py
pyledger/tests/base_test_assets.py
pyledger/tests/base_test_dump_restore_clear.py
pyledger/tests/base_test_ledger.py
pyledger/tests/base_test_price_history.py
pyledger/tests/base_test_profit_centers.py
pyledger/tests/base_test_revaluation.py
pyledger/tests/base_test_tax_codes.py
pyledger/tests/test_serialized_ledger_cache.py
pyledger/text_ledger.py

This PR goal is to rename settings to configuration.

Rename settings to configuration

---

docs/TextLedger.md
pyledger/text_ledger.py

Implements #106: Clarify TextLedger Folder Layout by renaming hard-coded paths.

Clarify TextLedger Folder Layout

---

pyledger/helpers.py
pyledger/tests/test_write_fixed_width_csv.py

This PR goal is to remove trailing whitespace in `Textledger`

Remove Trailing Whitespace in Textledger

---

.github/workflows/linter.yml
.github/workflows/security.yml
.github/workflows/tests.yml

This PR goal is to streamline GitHub workflow actions

Refactor github workflow actions

---

pyledger/ledger_engine.py
pyledger/tests/base_test.py
pyledger/tests/base_test_accounts.py

This PR goal is to update method interface to accept period instead of singe date.

`account_balance()` should accept period

---

pyledger/ledger_engine.py
pyledger/standalone_ledger.py
pyledger/tests/test_parse_account_range.py

This PR goal is to standardize account parameter treatment by introducing the `parse_account_range` method.

Define `parse_account_range` method

---

.github/workflows/tests.yml
setup.py

This PR goal is to clear setup dependencies.

Clear setup dependencies

---

pyledger/helpers.py
pyledger/tests/test_text_ledger_journal.py
pyledger/tests/test_write_fixed_width_csv.py
pyledger/text_ledger.py

This PR goal is to fix error writing empty ledger file.

Fix error writing empty ledger file

---

pyledger/standalone_ledger.py
pyledger/tests/base_test.py

This PR goal is to fix revaluation entries that have both account and contra fields are NA.

Account and contra are NA values in revaluation entries

---

pyledger/ledger_engine.py
pyledger/standalone_ledger.py

This PR goal is to extend `_single_account_balance()` to accept start and end dates.

Extend `_single_account_balance()` to accept start and end dates 

---

pyledger/__init__.py
pyledger/log_collector.py
pyledger/tests/test_log_collector.py

This PR goal is to copy LogCollector class from the accountbot package and test it.

Define `LogCollector` class

---

pyledger/constants.py
pyledger/ledger_engine.py
pyledger/tests/base_test.py
pyledger/tests/base_test_accounts.py

This PR goal is to introduce multiple accounts balances

Introduce multiple accounts balances

---

pyledger/helpers.py
pyledger/tests/test_prune_path.py

This PR goal is to add `prune_path()` method.

Add `prune_path()` method

---

pyledger/constants.py
pyledger/ledger_engine.py
pyledger/tests/base_test.py
pyledger/tests/base_test_accounts.py

This PR goal is to add `aggregate_account_balances()` method.

Add `aggregate_account_balances()` method

---

pyledger/helpers.py
pyledger/ledger_engine.py
pyledger/tests/test_first_elements_as_str.py
pyledger/tests/test_sanitize.py

This PR goal is to split sanitize_journal method into more readable chunks.

Split `sanitize_journal` method into more readable chunks

---

pyledger/ledger_engine.py
pyledger/tests/test_sanitize.py

This PR goal is to add functionality that handles transactions discarded due to rounding errors.

Transactions discarded due to rounding errors

---

pyledger/constants.py
pyledger/ledger_engine.py
pyledger/tests/base_test.py
pyledger/tests/base_test_accounts.py

This PR goal is to test `account_history()` method.

Test `account_history()` method

---

pyledger/ledger_engine.py
pyledger/tests/base_test_accounts.py

This PR goal is to clarify name and docstring for account balance methods.

Clarify name and docstring for account balance methods

---

pyledger/ledger_engine.py

This PR goal is to add `account_balances()` method.

Add `account_balances()` method

---

pyledger/constants.py
pyledger/helpers.py
pyledger/storage_entity.py
pyledger/tests/test_save_files.py

This PR goal is to allow for configurable file path column name.

Configurable file path column name

---

pyledger/constants.py
pyledger/memory_ledger.py
pyledger/standalone_ledger.py
pyledger/tests/base_test.py
pyledger/tests/base_test_reconciliation.py
pyledger/tests/base_test_standalone_ledger_dump_restore_clear.py
pyledger/tests/test_dump_restore.py
pyledger/tests/test_reconciliation.py
pyledger/tests/test_text_ledger_dump_restore_clear.py
pyledger/tests/test_text_ledger_reconciliation.py
pyledger/text_ledger.py

This PR goal is to define reconciliation data entity.

Define reconciliation data entity

---

pyledger/ledger_engine.py
pyledger/tests/test_sanitize.py

This PR goal is to add sanitize reconciliation method.

Add `sanitize_reconciliation()` method

---

pyledger/ledger_engine.py
pyledger/tests/base_test.py
pyledger/tests/base_test_reconciliation.py
pyledger/tests/test_text_ledger_reconciliation.py

This PR goal is to add reconcile logic.

Add reconcile logic
